export enum EventType {
    SERVER_CONNECTED,
    SERVER_DISCONNECTED,

    PLAYER_CONNECTING,
    PLAYER_CONNECTED,
    PLAYER_DISCONNECTED,
    PLAYER_INTERFACE_UPDATE,
    PLAYER_NAME_UPDATE,

    VEHICLE_CREATED,
    VEHICLE_DESTROYED,
    VEHICLE_JOIN_REQUEST,
    VEHICLE_UPDATE,
    VEHICLE_HIT_OBJECT,
    VEHICLE_PIT_STOP_START,
    VEHICLE_PIT_STOP_END,

    BUTTON_CREATED,
    BUTTON_REMOVED,
    BUTTON_UPDATE,
    BUTTON_CLICK,
    BUTTON_INPUT,
    BUTTON_CLEAR,

    PLAYER_LAYOUT_ADD,
    PLAYER_LAYOUT_REMOVE
}