export enum EventType {
    PLAYER_CONNECTING,
    PLAYER_CONNECTED,
    PLAYER_DISCONNECTED,
    PLAYER_INTERFACE_UPDATE,
    PLAYER_NAME_UPDATE,

    VEHICLE_CREATED,
    VEHICLE_DESTROYED,
    VEHICLE_JOIN_REQUEST,
    VEHICLE_UPDATE
}